name: pispapp
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

dependency_overrides:
  analyzer: '0.39.14'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fido2_client:
    git:
      url: git://github.com/mojaloop/contrib-fido2-flutter-lib
  logger: ^0.6.0
  international_phone_input: ^1.0.4
  intl_phone_number_input: ^0.6.0
  equatable: ^1.2.5
  local_auth: ^0.6.2+3
  get: ^3.25.4
  google_fonts: ^1.1.0
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  json_annotation: ^3.0.1
  firebase_core: ^0.4.5
  pin_code_fields: ^4.0.0
  flutter_secure_storage: ^3.3.3
  intl: ^0.16.1
  mockito: ^4.1.1
  flutter_web_auth: ^0.2.4
  cross_connectivity: ^1.0.2
  shared_preferences: ^0.5.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/pineapple.png