version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter analyze lib
      - run: flutter test
      # TODO: To be added later after encrypting google-services.json secret
      # - run: flutter -v build apk

