version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter analyze lib
      - run: flutter test
      # Missing google secrets json file: - run: flutter build apk --debug

